name: shop_app_flutter
description: A Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.2
  go_router: ^14.2.0
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
